#=============================================================================
# init.toml --- based on a mix of basic and dark power configuration example for SpaceVim
# Copyright (c) 2021 Andreas H. & Wang Shidong & Contributors
# Author: Andreas H.
# URL: https://github.com/andi-blafasl/spacevim.d
# License: GPLv3
#=============================================================================

# All SpaceVim option below [option] section
[options]
    # set spacevim theme. by default colorscheme layer is not loaded,
    # if you want to use more colorscheme, please load the colorscheme
    # layer
    colorscheme = "molokai"
    colorscheme_bg = "dark"
    # Disable guicolors in basic mode, many terminal do not support 24bit
    # true colors
    enable_guicolors = true
    # Disable statusline separator, if you want to use other value, please
    # install nerd fonts
    guifont = "SauceCodePro NF:h12"
    statusline_separator = "arrow"
    statusline_iseparator = "bar"
    buffer_index_type = 4
    #windows_index_type = 3
    enable_tabline_filetype_icon = false
    enable_statusline_mode = true
    statusline_unicode = true
    # Enable vim compatible mode, avoid changing origin vim key bindings
    vimcompatible = true
    relativenumber = false

# Enable autocomplete layer
[[layers]]
name = 'autocomplete'
auto_completion_return_key_behavior = "complete"
auto_completion_tab_key_behavior = "cycle"

[[layers]]
name = 'shell'
default_position = 'top'
default_height = 30

[[layers]]
  name = "colorscheme"

[[layers]]
  name = "VersionControl"

[[layers]]
  name = "git"
  git_plugin = 'fugitive'

